# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5743d1709f52925bb1fe5f3e8d39a0a08b94ed7e74aa748eaccbcc2448e0c3e48c40f69db8676367778d433e58a06a1f2df34638bfc9ba4e6003ce4e04535c53

test:
  secret_key_base: 28a48a30acbd74e98cbdfbc46ff8c60288add6f80496f53343143ea312e60545f3a5918293df9b7ccf83089893a2af1e5b3b4189cc6567402d8877ddfaf78e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
